### ISSUE TITLE
trans to kitti problem

### ISSUE THREAD

**Issue by morte2025** [naurril/SUSTechPOINTS#106]
Thanks for your excellent work.
when using trans_kitti_labels.py, I got the following error. 

Traceback (most recent call last):
  File "trans_kitti_labels.py", line 198, in <module>
    trans_detection_label(src_label, src_calib, tgt_label)
  File "trans_kitti_labels.py", line 125, in trans_detection_label
    filtered_objs = [x for x in objs]
  File "trans_kitti_labels.py", line 125, in <listcomp>
    filtered_objs = [x for x in objs]
  File "trans_kitti_labels.py", line 124, in <lambda>
    objs = map(lambda l: parse_one_detection_obj(inv_m, l), lines)
  File "trans_kitti_labels.py", line 92, in parse_one_detection_obj
    pos = np.array([float(words[11]), float(words[12]), float(words[13]), 1]).T
IndexError: list index out of range

**Comment by naurril** [comment]
this tool is translating KITTI to our format, not to KITTI

**Comment by morte2025** [comment]
Thank you for your reply. Then how to do the opposite, translating the json file to kitti txt label file.

**Comment by SH-Tan** [comment]
meet the same question

**Comment by AgapeGithub** [comment]
Hello guys,

Did you find a solution to convert the export format to Kitti please?

Thank you very much

**Comment by YKE999** [comment]
> Thank you for your reply. Then how to do the opposite, translating the json file to kitti txt label file.

https://github.com/naurril/SUSTechPOINTS/issues/146#issuecomment-1507801603 

this one may help

**Comment by YKE999** [comment]
> 

https://github.com/naurril/SUSTechPOINTS/issues/146#issuecomment-1507801603

check this one

**Comment by YKE999** [comment]
> Hello guys,
> 
> Did you find a solution to convert the export format to Kitti please?
> 
> Thank you very much

https://github.com/naurril/SUSTechPOINTS/issues/146#issuecomment-1507801603

check this one

**Comment by yaobaishen** [comment]
> > Hello guys,
> > Did you find a solution to convert the export format to Kitti please?
> > Thank you very much
> 
> [#146 (comment)](https://github.com/naurril/SUSTechPOINTS/issues/146#issuecomment-1507801603)
> 
> check this one

thanks the tips, I have succeed to trans to kitti format using the above code.
