### ISSUE TITLE
fail to launch via `python main.py` in fusion-branch

### ISSUE THREAD

**Issue by zheyuanWang** [naurril/SUSTechPOINTS#143]
Hi, 
I got the following error when running `python main.py`  in fusion branch:
```
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    print(datacfg['global']['rootdir'])
  File "/home/lib/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'global'
```

It seems related to config files.  

I  removed all suffixes (`.example`) of files in `/conf` folder, but it did not work.

Could you please provide a README on how to setup the required config?

**Comment by naurril** [comment]
./conf/data.conf

```
[global]
rootdir=./data

```
