### ISSUE TITLE
不能shift和ctrl画框了，只能右键new新框，求助

### ISSUE THREAD

**Issue by kuaiqushangzixiba** [naurril/SUSTechPOINTS#149]
如题，shift和ctrl框选没有反应

**Comment by naurril** [comment]
看一下浏览器console log有没有报错

**Comment by kuaiqushangzixiba** [comment]
> 看一下浏览器console log有没有报错
红色的如下： 
select rect points 1978
annotation.js:296
**Uncaught TypeError: Cannot read properties of undefined (reading 'color')**
    at Annotation.createCuboid (annotation.js:296:103)
    at Annotation.add_box (annotation.js:324:25)
    at Editor.create_box_by_points (editor.js:1561:43)
    at Editor.handleSelectRect (editor.js:1470:24)
    at Mouse.handleSelectRect (editor.js:232:46)
    at Mouse.onMouseUp (mouse.js:213:22)
    at HTMLDivElement.on_mouse_up (mouse.js:152:34)
Annotation.createCuboid @ annotation.js:296
Annotation.add_box @ annotation.js:324
Editor.create_box_by_points @ editor.js:1561
Editor.handleSelectRect @ editor.js:1470
(anonymous) @ editor.js:232
Mouse.onMouseUp @ mouse.js:213
on_mouse_up @ mouse.js:152

**Comment by naurril** [comment]
是不是改了代码了，objcfg里面是不是没有写color

**Comment by kuaiqushangzixiba** [comment]
谢谢！我删除了一些obj.js中的类别，现在把他们都恢复了没有这个错误了
