### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by chenxyyy** [naurril/SUSTechPOINTS#180]
使用的是docker部署方式，在使用`dockerfile`创建好镜像，并使用对应的命令创建好容器后，运行`python main.py` 出现以下错误。

```bash

..................

CherryPy Checker:
The config entry 'auth.require' is invalid, because the 'auth' config namespace is unknown.
section: [/views]

CherryPy Checker:
'/root/SUSTechPOINTS/./temp' (root + dir) is not an existing filesystem path.
section: [/temp]
root: '/root/SUSTechPOINTS'
dir: './temp'

CherryPy Checker:
'/root/SUSTechPOINTS/./views' (root + dir) is not an existing filesystem path.
section: [/views]
root: '/root/SUSTechPOINTS'
dir: './views'

CherryPy Checker:
'/root/SUSTechPOINTS/./assets' (root + dir) is not an existing filesystem path.
section: [/assets]
root: '/root/SUSTechPOINTS'
dir: './assets'

[15/Dec/2023:09:43:43] ENGINE Started monitor thread 'Autoreloader'.
[15/Dec/2023:09:43:45] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7fa6a3d032e0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/portend.py", line 122, in free
    Checker(timeout=0.1).assert_free(host, port)
  File "/usr/local/lib/python3.8/dist-packages/portend.py", line 71, in assert_free
    list(itertools.starmap(self._connect, info))
  File "/usr/local/lib/python3.8/dist-packages/portend.py", line 87, in _connect
    raise PortNotFree(tmpl.format(**locals()))
portend.PortNotFree: Port 8081 is in use on 0.0.0.0.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cherrypy/process/wspbus.py", line 230, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/cherrypy/_cpserver.py", line 180, in start
    super(Server, self).start()
  File "/usr/local/lib/python3.8/dist-packages/cherrypy/process/servers.py", line 177, in start
    portend.free(*self.bind_addr, timeout=Timeouts.free)
  File "/usr/local/lib/python3.8/dist-packages/portend.py", line 126, in free
    raise Timeout("Port {port} not free on {host}.".format(**locals()))
portend.Timeout: Port 8081 not free on 0.0.0.0.

[15/Dec/2023:09:43:45] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cherrypy/process/wspbus.py", line 268, in start
    self.publish('start')
  File "/usr/local/lib/python3.8/dist-packages/cherrypy/process/wspbus.py", line 248, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: Timeout('Port 8081 not free on 0.0.0.0.')

[15/Dec/2023:09:43:45] ENGINE Bus STOPPING
[15/Dec/2023:09:43:45] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8081)) already shut down
[15/Dec/2023:09:43:45] ENGINE Stopped thread 'Autoreloader'.
[15/Dec/2023:09:43:45] ENGINE Bus STOPPED
[15/Dec/2023:09:43:45] ENGINE Bus EXITING
[15/Dec/2023:09:43:45] ENGINE Bus EXITED


```

**Comment by bilibilicharger** [comment]
Do you resolve this problem?
